---

# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
- name: AccuInsight+ Kubernetes | Set Kernel modules for CRI-O (1/2)
  become: yes
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - 'overlay'
    - 'br_netfilter'


# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
- name: AccuInsight+ Kubernetes | Set Kernel modules for CRI-O (2/2)
  become: yes
  lineinfile:
    path: /etc/modules-load.d/cri-o.conf
    line: "{{ item }}"
    state: present
    owner: root
    group: root
    mode: '0644'
    create: yes
  loop:
    - 'overlay'
    - 'br_netfilter'


# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
- name: AccuInsight+ Kubernetes | Set Kernel parameters for CRI-O
  become: yes
  sysctl:
    name: "{{ item.key }}"
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  loop:
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
  loop_control:
    label: "{{ item.value }}, {{ item.key }}"


- import_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'


- import_tasks: debian.yaml
  when: ansible_os_family == 'Debian'


