---

- name: AccuInsight+ Loki | Add Chart Repository 'loki'
  when:
    - not accu_offline_enabled | bool
    - inventory_hostname in groups['kube-master']
  become: yes
  helm_repository:
    name: harbor
    url: https://github.com/grafana/helm-charts/tree/main/charts/loki-stack
    state: present
  no_log: true

- name: AccuInsight+ Loki | Set chart location
  when:
    - inventory_hostname in groups['kube-master']
  set_fact:
    chartname: >-
      {% if accu_offline_enabled | bool                                                  %}
      {{ accu_offline_target }}/{{ component }}/charts/loki-stack-{{ accu_loki_version }}.tgz
      {% else                                                                            %}
      loki/loki
      {% endif                                                                           %}
  run_once: yes

# READ: https://github.com/grafana/helm-charts/tree/main/charts/loki-stack
- name: AccuInsight+ Loki | Deploy {{ accu_loki_release }}
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  helm_cmd:
    name: "{{ chartname }}"
    release: "{{ accu_loki_release }}"
    version: "{{ accu_loki_version }}"
    namespace: "{{ accu_loki_namespace }}"
    state: present
    update_cache: no
    force: yes
    wait: true
    options:
      - '--set fullnameOverride={{ accu_loki_release }}'
      - '--set promtail.enabled=true'
      - '--set promtail.loki.serviceName={{ accu_loki_release }}' 
      - '--set promtail.extraVolumes[0].name={{ accu_loki_syslog_volume_name }}'
      - '--set promtail.extraVolumes[0].hostPath.path={{ accu_loki_syslog_volume_path }}'
      - '--set promtail.extraVolumeMounts[0].name={{ accu_loki_syslog_mount_name }}'
      - '--set promtail.extraVolumeMounts[0].mountPath={{ accu_loki_syslog_mount_path }}'
      - '--set promtail.extraScrapeConfigs[0].job_name={{ accu_loki_syslog_job_name }}'
      - '--set promtail.extraScrapeConfigs[0].static_configs[0].labels.job={{ accu_loki_syslog_label_job }}'
      - '--set promtail.extraScrapeConfigs[0].static_configs[0].labels.host={{ accu_loki_syslog_label_host }}'
      - '--set promtail.extraScrapeConfigs[0].static_configs[0].labels.__path__={{ accu_loki_syslog_label_path }}'

