---

- name: AccuInsight+ Helm | Install helm on masters
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  unarchive:
    src: "{{ accu_offline_target }}/{{ component }}/files/helm-v{{ accu_helm_version }}-linux-amd64.tar.gz"
    dest: /usr/bin
    remote_src: yes
    owner: root
    group: root
    exclude:
      - 'LICENSE'
      - 'README.md'
    extra_opts:
      - '--strip-components=1'


- name: AccuInsight+ Helm | Install helm plugin (push) on masters
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
    HOME=$(grep ^{{ item }}: /etc/passwd | cut -d ':' -f 6)

    if [ $HOME ] # if the user exists ...
    then
      mkdir -p $HOME/.local/share/helm/plugins/helm-push

      tar xzf {{ accu_offline_target }}/{{ component }}/files/helm-push_0.9.0_linux_amd64.tar.gz -C $HOME/.local/share/helm/plugins/helm-push

      chown -R $(id {{ item }} -u):$(id {{ item }} -g) $HOME/.local/share/helm
    fi
  args:
    executable: /bin/bash
  loop: "{{ kube_admin_users }}"


#- name: AccuInsight+ Helm | Prepare helm plugin (push) on masters
#  when:
#    - inventory_hostname in groups['kube-master']
#  become: yes
#  file:
#    path: /root/.local/share/helm/plugins/helm-push
#    state: directory


#- name: AccuInsight+ Helm | Install helm plugin (push) on masters
#  when:
#    - inventory_hostname in groups['kube-master']
#  become: yes
#  unarchive:
#    src: "{{ accu_offline_target }}/{{ component }}/files/helm-push_0.9.0_linux_amd64.tar.gz"
#    dest: /root/.local/share/helm/plugins/helm-push
#    remote_src: yes


- name: AccuInsight+ Helm | Update charts repository (obsolete stable)
  when:
    - not accu_offline_enabled | bool
    - inventory_hostname in groups['kube-master']
  become: yes
  helm_repository: 
    name: stable
    url: "{{ accu_helm_stable_repo }}"
    state: present
  no_log: true
  

- name: AccuInsight+ Helm | Update charts repository (metadata)
  when:
    - not accu_offline_enabled | bool
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
      helm repo update
  args:
    executable: /bin/bash


- name: AccuInsight+ Helm | Set command completion for Helm
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
      helm completion bash > /etc/bash_completion.d/helm
  args:
    executable: /bin/bash


