---

- name: AccuInsight+ Kubernetes | Master
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  block:

    # READ: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
    # READ: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/
    - name: AccuInsight+ Kubernetes | Check masters' initialization status
      stat:
        path: /var/lib/kubelet/config.yaml
      register: init_status
    
    
    - name: AccuInsight+ Kubernetes | Prepare for Kubernetes '{{ kube_version }}' images
      when:
        - not init_status.stat.exists
        - not accu_offline_enabled | bool
      shell: |
        kubeadm config images pull --config {{ accu_manifests_location }}/{{ component }}/init-master-config.yaml
      args:
        executable: /bin/bash
    
    
    - name: AccuInsight+ Kubernetes | Initialize first master
      when:
        - inventory_hostname == groups['kube-master'][0]
        - not init_status.stat.exists
      shell: |
        kubeadm init --config {{ accu_manifests_location }}/{{ component }}/init-master-config.yaml --upload-certs --ignore-preflight-errors DirAvailable--etc-kubernetes-manifests
      args:
        executable: /bin/bash
      register: init_result
      failed_when: init_result is failed
      until: init_result is succeeded
      retries: 3
      delay: 60
      notify:
        - Kubelet | Restart


    # NOTE: This task prepares tokens and certs if they are expired.
    - name: AccuInsight+ Kubernetes | Prepare tokens and certs for node joining
      when:
        - inventory_hostname == groups['kube-master'][0]
        - init_status.stat.exists
      shell: |
        # Generate bootstrap token for joining nodes (master and worker) if not exists (expired)
        if [[ -z $(kubeadm token list | grep accuxx.0123456789abcdef) ]]
        then
          kubeadm init phase bootstrap-token --config {{ accu_manifests_location }}/{{ component }}/init-master-config.yaml
        fi
        # Upload certs for joining additional masters if not exists (expired)
        if [[ -z $(kubectl -n kube-system get secrets | grep kubeadm-certs) ]]
        then
          kubeadm init phase upload-certs --upload-certs --config {{ accu_manifests_location }}/{{ component }}/init-master-config.yaml
        fi
      args:
        executable: /bin/bash


    - name: AccuInsight+ Kubernetes | Initialize other master
      when:
        - inventory_hostname != groups['kube-master'][0]
        - not init_status.stat.exists
      shell: |
        kubeadm join --config {{ accu_manifests_location }}/{{ component }}/join-master-config.yaml --ignore-preflight-errors DirAvailable--etc-kubernetes-manifests
      args:
        executable: /bin/bash
      register: join_result
      failed_when: join_result is failed
      until: join_result is succeeded
      retries: 3
      delay: 60
      notify:
        - Kubelet | Restart


    # READ: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#more-information
    - name: AccuInsight+ Kubernetes | Set Superuser privileges for kube_admin_users
      shell: |
        # Set home directory of kube_admin_users.
        HOME=$(grep ^{{ item }}: /etc/passwd | cut -d ':' -f 6)

        if [ $HOME ] # if the user exists ...
        then
          # Create directory for kube_admin_users.
          mkdir -p $HOME/.kube

          # Copy kubeconfig and change ownership for users.
          cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
          chown -R $(id {{ item }} -u):$(id {{ item }} -g) $HOME/.kube

          # Set CRI socket permission for users.
          if [ "{{ kube_cri }}" == "docker" ]
          then
            setfacl -m user:{{ item }}:rw /var/run/docker.sock
          fi

          if [ "{{ kube_cri }}" == "containerd" ]
          then
            setfacl -m user:{{ item }}:x /run/containerd
            setfacl -m user:{{ item }}:rw /run/containerd/containerd.sock
          fi

          if [ "{{ kube_cri }}" == "cri-o" ]
          then
            setfacl -m user:{{ item }}:x /var/run/crio
            setfacl -m user:{{ item }}:rw /var/run/crio/crio.sock
          fi
        fi
      args:
        executable: /bin/bash
      loop: "{{ kube_admin_users }}"
    
    
    - name: AccuInsight+ Kubernetes | Set command completion for Kubernetes
      shell: |
        kubeadm completion bash > /etc/bash_completion.d/kubeadm
        kubectl completion bash > /etc/bash_completion.d/kubectl
      args:
        executable: /bin/bash


