---

- name: Print inventory hostname
  debug:
    msg: "{{ inventory_hostname }}"

- name: Print kernel version
  debug:
    msg: "{{ ansible_kernel }}"

- name: Print loadbalancer address
  debug:
    msg: "{{ ext_lb_addr }}"

