---

- import_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'


- import_tasks: debian.yaml
  when: ansible_os_family == 'Debian'


# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
- name: AccuInsight+ Kubernetes | Create configuration directories for Docker
  become: yes 
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop:
    # Docker config directory
    - { path: /etc/docker }
    # Docker systemd drop-in directory
    - { path: /etc/systemd/system/docker.service.d }


# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
- name: AccuInsight+ Kubernetes | Create service override for Docker
  become: yes
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - CRI | Docker | Restart
    - CRI | Docker | Wait for Ready


# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
- name: AccuInsight+ Kubernetes | Create service drop-ins for Docker
  become: yes
  template:
    src: "{{ item.path }}/{{ item.file }}.j2"
    dest: "/etc/systemd/system/docker.service.d/{{ item.file }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    # Docker cgroup driver
    - { path: drop-in, file: accu-cgroup.conf }
    # Docker insecure registry
    - { path: drop-in, file: accu-registry.conf }
  notify:
    - CRI | Docker | Restart
    - CRI | Docker | Wait for Ready


