---

- name: AccuInsight+ Helm Operator | Create manifests directory for {{ component }}
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  file:
    path: "{{ accu_manifests_location }}/{{ component }}"
    owner: root
    group: root
    mode: '0755'
    recurse: true


- name: AccuInsight+ Helm Operator| Create manifests for Helm Operator
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  template:
    src: helm-operator-crd.yaml.j2
    dest: "{{ accu_manifests_location }}/{{ component }}/helm-operator-crd.yaml"
    owner: root
    group: root
    mode: '0644'
  run_once: true


- name: AccuInsight+ Helm Operator | Apply manifests for Helm Operator
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
      kubectl apply -f {{ accu_manifests_location }}/{{ component }}/helm-operator-crd.yaml
  args:
    executable: /bin/bash  
  run_once: true


- name: AccuInsight+ Helm Operator | Add Chart Repository 'fluxcd'
  when:
    - not accu_offline_enabled | bool
    - inventory_hostname in groups['kube-master']
  become: yes
  helm_repository:
    name: fluxcd
    url: https://charts.fluxcd.io
    state: present
  no_log: true
  run_once: true


- name: AccuInsight+ Helm Operator | Set chart location
  when:
    - inventory_hostname in groups['kube-master']
  set_fact:
    chartname: >-
      {% if accu_offline_enabled | bool                                                                %}
      {{ accu_offline_target }}/{{ component }}/charts/helm-operator-{{ accu_helm_operator_version }}.tgz
      {% else                                                                                          %}
      fluxcd/helm-operator
      {% endif                                                                                         %}
  run_once: yes


- name: AccuInsight+ Helm Operator | Deploy {{ accu_helm_operator_release }}
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  helm_cmd:
    name: "{{ chartname }}"
    release: "{{ accu_helm_operator_release }}"
    namespace: "{{ accu_helm_operator_namespace }}"
    version: "v{{ accu_helm_operator_version }}"
    state: present
    update_cache: no
    force: yes
    wait: true
    options:
      - '--set fullnameOverride={{ accu_helm_operator_release }}'
      - '--set helm.versions=v3'
  run_once: true


