---

redhat:

  repos:
    - name: Kubernetes
      url: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      key: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    - name: Docker
      url: https://download.docker.com/linux/centos/7/$basearch/stable
      key: https://download.docker.com/linux/centos/gpg
    - name: OCI
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_{{ ansible_distribution_major_version }}/"
      key: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_{{ ansible_distribution_major_version }}/repodata/repomd.xml.key"
    - name: "CRI-O-{{ crio_version }}"
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/CentOS_{{ ansible_distribution_major_version }}/"
      key: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/CentOS_{{ ansible_distribution_major_version }}/repodata/repomd.xml.key"
    - name: Ceph
      url: "https://download.ceph.com/rpm-{{ accu_rook_ceph_image_version }}/el{{ ansible_distribution_major_version }}/$basearch"
      key: https://download.ceph.com/keys/release.asc
  
  pkgs:
    core: >
          [
            "kubeadm-{{ kube_version }} kubelet-{{ kube_version }} kubectl-{{ kube_version }}",
            {% if kube_cri == 'containerd' %}
            "containerd.io-{{ containerd_version }}",
            {% endif                       %}
            {% if kube_cri == 'cri-o'      %}
            "cri-o podman",
            {% endif                       %}
            {% if kube_cri == 'docker'     %}
            "docker-ce-{{ docker_version }} docker-ce-cli-{{ docker_version }}",
            {% endif                       %}
          ]
    reqs:
      # for ansible
      - 'rsync'
      # for kubernetes
      #- 'skopeo'
      # for accu-accelerator (multiple versions of kernel)
  #    - '{% for kv in accu_accelerator_kernel_version %} kernel-{{ kv }} kernel-devel-{{ kv }} kernel-tools-{{ kv }} kernel-tools-libs-{{ kv }} kernel-headers-{{ kv }} {% endfor %}'
  #    - 'kernel-{{ accu_accelerator_kernel_version }}'
  #    - 'kernel-devel-{{ accu_accelerator_kernel_version }}'
  #    - 'kernel-tools-{{ accu_accelerator_kernel_version }}'
  #    - 'kernel-tools-libs-{{ accu_accelerator_kernel_version }}'
  #    - 'kernel-headers-{{ accu_accelerator_kernel_version }}'
      - 'elfutils-libelf-devel'
      - 'gcc'
      - 'make'
      # for accu-accelerator (nvidia)
      - 'patch'
      - 'nvidia-docker2'
      - 'nvidia-container-runtime'
      - 'nvidia-container-toolkit'
      # for accu-nfs-server and accu-nfs-provisioner
      - 'nfs-utils'
      # for accu-repository-server
      - 'httpd'
      - 'createrepo_c'
      # for accu-rook-ceph
      - 'ceph-common'
      - 'ceph-fuse'
      - 'lvm2'
      - 'gdisk'
      # for accu-tools
      - 'bash-completion'
      # for containerd and docker
      # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
      # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
      - 'yum-utils'
      - 'device-mapper-persistent-data'
      - 'lvm2'
      # for debugging utilities
      - 'net-tools'
      - 'bind-utils'
      - 'lsof'
      - 'pciutils'
      - 'lshw'
  
