###############################################################################
#                                                                             #
# Compatiblity matrix for Kubernetes components                               #
#                                                                             #
###############################################################################

# SupportedEtcdVersion constant in kubeadm source code.
# https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L464-L477
matrix_etcd:
  '1.13': "3.2.24"
  '1.14': "3.3.10"
  '1.15': "3.3.10"
  '1.16': "3.3.17-0"
  '1.17': "3.4.3-0"
  '1.18': "3.4.3-0"
  '1.19': "3.4.13-0"
  '1.20': "3.4.13-0"
  '1.21': "3.4.13-0"
  '1.22': "3.5.0-0"
  '1.23': "3.5.0-0"

supported_etcd: "{{ matrix_etcd[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')] }}"


# PauseVersion constant in kubeadm source code.
matrix_pause:
  '1.13': "3.1"   # https://github.com/kubernetes/kubernetes/blob/release-1.13/cmd/kubeadm/app/constants/constants.go#L256
  '1.14': "3.1"   # https://github.com/kubernetes/kubernetes/blob/release-1.14/cmd/kubeadm/app/constants/constants.go#L263
  '1.15': "3.1"   # https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/constants/constants.go#L264
  '1.16': "3.1"   # https://github.com/kubernetes/kubernetes/blob/release-1.16/cmd/kubeadm/app/constants/constants.go#L266
  '1.17': "3.1"   # https://github.com/kubernetes/kubernetes/blob/release-1.17/cmd/kubeadm/app/constants/constants.go#L269
  '1.18': "3.2"   # https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kubeadm/app/constants/constants_unix.go#L26
  '1.19': "3.2"   # https://github.com/kubernetes/kubernetes/blob/release-1.19/cmd/kubeadm/app/constants/constants_unix.go#L26
  '1.20': "3.2"   # https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/constants/constants_unix.go#L26
  '1.21': "3.4.1" # https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/kubeadm/app/constants/constants.go#L403
  '1.22': "3.5"   # https://github.com/kubernetes/kubernetes/blob/release-1.22/cmd/kubeadm/app/constants/constants.go#L397
  '1.23': "3.5"   # https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L402

supported_pause: "{{ matrix_pause[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')] }}"


# CoreDNSVersion contant in kubeadm source code.
matrix_coredns:
  '1.13': "1.2.6"  # https://github.com/kubernetes/kubernetes/blob/release-1.13/cmd/kubeadm/app/constants/constants.go#L335
  '1.14': "1.3.1"  # https://github.com/kubernetes/kubernetes/blob/release-1.14/cmd/kubeadm/app/constants/constants.go#L342
  '1.15': "1.3.1"  # https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/constants/constants.go#L334
  '1.16': "1.6.2"  # https://github.com/kubernetes/kubernetes/blob/release-1.16/cmd/kubeadm/app/constants/constants.go#L336
  '1.17': "1.6.5"  # https://github.com/kubernetes/kubernetes/blob/release-1.17/cmd/kubeadm/app/constants/constants.go#L339
  '1.18': "1.6.7"  # https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kubeadm/app/constants/constants.go#L343
  '1.19': "1.7.0"  # https://github.com/kubernetes/kubernetes/blob/release-1.19/cmd/kubeadm/app/constants/constants.go#L335
  '1.20': "1.7.0"  # https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/constants/constants.go#L353
  '1.21': "v1.8.0" # https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/kubeadm/app/constants/constants.go#L334
  '1.22': "v1.8.4" # https://github.com/kubernetes/kubernetes/blob/release-1.22/cmd/kubeadm/app/constants/constants.go#L328
  '1.23': "v1.8.4" # https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L333

supported_coredns: "{{ matrix_coredns[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')] }}"


###############################################################################
#                                                                             #
# Compatiblity matrix for Kubernetes runtimes                                 #
#                                                                             #
###############################################################################

############
# DOCKER   #
############

# The recommended docker version will be selected automatically if 'kube_cri_version' is not defined.
docker_matrix: # docker_matrix['kube_version']
  # https://v1-17.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
  # On each of your machines, install Docker. Version 19.03.4 is recommended, but 1.13.1, 17.03, 17.06, 17.09, 18.06 and 18.09 are known to work as well.
  # https://github.com/kubernetes/kubernetes/blob/v1.17.17/vendor/k8s.io/system-validators/validators/docker_validator.go#L52
  '1.17': "19.03.4"
  # https://v1-18.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
  # On each of your machines, install Docker. Version 19.03.11 is recommended, but 1.13.1, 17.03, 17.06, 17.09, 18.06 and 18.09 are known to work as well.
  # https://github.com/kubernetes/kubernetes/blob/v1.18.20/vendor/k8s.io/system-validators/validators/docker_validator.go#L52
  '1.18': "19.03.11"
  # https://v1-19.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
  # The Kubernetes release notes list which versions of Docker are compatible with that version of Kubernetes.
  # https://github.com/kubernetes/kubernetes/blob/v1.19.12/vendor/k8s.io/system-validators/validators/docker_validator.go#L52
  '1.19': "19.03.14"
  # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
  # The Kubernetes release notes list which versions of Docker are compatible with that version of Kubernetes.
  # https://github.com/kubernetes/kubernetes/blob/v1.21.2/vendor/k8s.io/system-validators/validators/docker_validator.go#L52
  '1.20': "19.03.14"
  # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
  # You can find the latest validated version of Docker in this dependencies file.
  # https://github.com/kubernetes/kubernetes/blob/v1.21.2/vendor/k8s.io/system-validators/validators/docker_validator.go#L52
  '1.21': "20.10.7"
  # NOTE: https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/
  # If you’re rolling your own clusters, you will also need to make changes to avoid your clusters breaking.
  # At v1.20, you will get a deprecation warning for Docker. When Docker runtime support is removed in a future release
  # (currently planned for the 1.22 release in late 2021) of Kubernetes it will no longer be supported
  # and you will need to switch to one of the other compliant container runtimes, like containerd or CRI-O.

docker_version: "{{ lookup('vars', 'kube_cri_version') | default(docker_matrix[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')], true) }}"


##############
# CONTAINERD #
##############

# NOTE: There is no clear support matrix for containerd.
#       Following matrix is decided according to what version of 'pause' is used by containerd and kubernetes.
# The recommended containerd version will be selected automatically if 'kube_cri_version' is not defined.
containerd_matrix: # containerd_matrix['kube_version']
  # https://v1-17.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
  '1.17': "1.3.9" # pause 3.1
  # https://v1-18.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
  '1.18': "1.4.9" # pasue 3.2
  # https://v1-19.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
  # The Kubernetes release notes list which versions of containerd are compatible with that version of Kubernetes.
  '1.19': "1.4.9" # pause 3.2
  # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
  # The Kubernetes release notes list which versions of containerd are compatible with that version of Kubernetes.
  '1.20': "1.4.9" # pause 3.2
  # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
  # No more comment on compatibility.
  '1.21': "1.4.9" # pause: kubernetes uses 3.4.1 but containerd 1.4.x uses 3.2.
                  # I'd like to set containerd's sandbox_image to 3.4.1.
  '1.22': "1.4.9" # pause: kubernetes uses 3.5 but containerd 1.4.x uses 3.2.
                  # I'd like to set containerd's sandbox_image to 3.5.
  '1.23': "1.4.9" # pause: kubernetes uses 3.5 but containerd 1.4.x uses 3.2.
                  # I'd like to set containerd's sandbox_image to 3.5.

containerd_version: "{{ lookup('vars', 'kube_cri_version') | default(containerd_matrix[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')], true) }}"


##############
# CRI-O      #
##############

# CRI-O compatiblity matrix for Kubernetes
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
# The CRI-O major and minor versions must match the Kubernetes major and minor versions.
# https://github.com/cri-o/cri-o#compatibility-matrix-cri-o--kubernetes


# The recommended cri-o version will be selected automatically if 'kube_cri_version' is not defined.
crio_matrix: # crio_matrix['kube_version']
  '1.17': "1.17"
  '1.18': "1.18"
  '1.19': "1.19"
  '1.20': "1.20"
  '1.21': "1.21" # pause: kubernetes use 3.4.1 but cri-o uses 3.5. NEED FURTHER INVESTIGATION.
  '1.22': "1.22" # pause: kubernetes use 3.4.1 but cri-o uses 3.5. NEED FURTHER INVESTIGATION.
  # '1.23': "1.23" # cri-o doesn't support kubernetes 1.23 yet (2021.08.31)

crio_version: "{{ lookup('vars', 'kube_cri_version') | default(crio_matrix[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')], true) }}"


