---

# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
- name: AccuInsight+ Kubernetes | Set Kernel modules for containerd (1/2)
  become: yes 
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - 'overlay'
    - 'br_netfilter'


# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
- name: AccuInsight+ Kubernetes | Set Kernel modules for containerd (2/2)
  become: yes 
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "{{ item }}"
    state: present
    owner: root
    group: root
    mode: '0644'
    create: yes 
  loop:
    - 'overlay'
    - 'br_netfilter'


# READ: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
- name: AccuInsight+ Kubernetes | Set Kernel parameters for containerd
  become: yes 
  sysctl:
    name: "{{ item.key }}"
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes 
  loop:
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }


- import_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'


- import_tasks: debian.yaml
  when: ansible_os_family == 'Debian'

- name: AccuInsight+ Kubernetes | Create crictl configuration for containerd
  become: yes
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: '0644'


