---

accu:

  os:
    distro: "{{ ansible_distribution | lower }}"
    version: "{{ ansible_distribution_version }}"

  apache:
    name: httpd
    pkgs:
      - 'httpd-*'
      - 'httpd-filesystem-*'
      - 'httpd-tools-*'
      - 'apr-*'
      - 'apr-util-*'
      - 'apr-util-bdb-*'
      - 'apr-util-openssl-*'
      - 'centos-logos-httpd-*'
      - 'mailcap-*'
      - 'mod_http2-*'

  createrepo:
    pkgs:
      - 'createrepo_c-*'
      - 'createrepo_c-libs-*'
      - 'drpm-*'
      - 'libmodulemd-*'

  repo:
    online: # Repositories to disable in air-gapped environment.
      - repo: CentOS-Base
        section: BaseOS
      - repo: CentOS-AppStream
        section: AppStream
      - repo: CentOS-Extras
        section: extras
    offline: # Repositories to enable in air-gapped environment.
      - name: AccuInsight
        file: AccuInsight
        desc: AccuInsight+ Repository - {{ ansible_distribution }} {{ ansible_distribution_version }}
        base: "{% for host in groups['accu-pkg-server'] %}http://{{ hostvars[host]['private_ip'] }}:{{ accu_package_repository_port }}/accuinsight {% endfor %}"

