---

accu:

  os:
    distro: "{{ ansible_distribution | lower }}"
    version: "{{ ansible_distribution_version }}"

  apache:
    name: httpd
    pkgs:
      - 'httpd-*'
      - 'httpd-filesystem-*'
      - 'httpd-tools-*'
      - 'apr-*'
      - 'apr-util-*'
      - 'apr-util-bdb-*'
      - 'apr-util-openssl-*'
      - 'mailcap-*'
      - 'mod_http2-*'
      - 'redhat-logos-httpd-*'

  createrepo:
    pkgs:
      - 'createrepo_c-*'
      - 'createrepo_c-libs-*'
      - 'drpm-*'
      - 'libmodulemd-2.9.4-2.el8.x86_64.rpm'

  repo:
    online: # Repositories to disable in air-gapped environment.
      - repo: redhat-rhui
        section: rhel-8-baseos-rhui-rpms
      - repo: redhat-rhui
        section: rhel-8-appstream-rhui-rpms
      - repo: redhat-rhui-client-config
        section: rhui-client-config-server-8
    offline: # Repositories to enable in air-gapped environment.
      - name: AccuInsight
        file: AccuInsight
        desc: AccuInsight+ Repository - {{ ansible_distribution }} {{ ansible_distribution_version }}
        base: "{% for host in groups['accu-pkg-server'] %}http://{{ hostvars[host]['private_ip'] }}:{{ accu_package_repository_port }}/accuinsight {% endfor %}"

