---

accu:

  os:
    distro: "{{ ansible_distribution | lower }}"
    version: "{{ ansible_distribution_version }}"

  apache:
    name: httpd
    pkgs:
      - 'httpd-*'
      - 'httpd-tools-*'
      - 'apr-*'
      - 'apr-util-*'
      - 'mailcap-*'
      - 'redhat-logos-*'

  createrepo:
    pkgs:
      - 'createrepo_c-*'
      - 'createrepo_c-libs-*'

  repo:
    online: # Repositories to disable in air-gapped environment.
      - repo: redhat-rhui
        section: rhel-7-server-rhui-rpms
      - repo: redhat-rhui
        section: rhel-7-server-rhui-rh-common-rpms
      - repo: redhat-rhui-client-config
        section: rhui-client-config-server-7
    offline: # Repositories to enable in air-gapped environment.
      - name: AccuInsight
        file: AccuInsight
        desc: AccuInsight+ Repository - {{ ansible_distribution }} {{ ansible_distribution_version }}
        base: "{% for host in groups['accu-pkg-server'] %}http://{{ hostvars[host]['private_ip'] }}:{{ accu_package_repository_port }}/accuinsight {% endfor %}"

