---

accu:

  os:
    distro: "{{ ansible_distribution | lower }}"
    version: "{{ ansible_distribution_version }}"

  apache:
    name: apache2
    pkgs:
      - 'apache2_*'
      - 'apache2-bin_*'
      - 'apache2-data_*'
      - 'apache2-utils_*'
      - 'libapr1_*'
      - 'libaprutil1_*'
      - 'libaprutil1-dbd-sqlite3_*'
      - 'libaprutil1-ldap_*'
      - 'libjansson4_*'
      - 'liblua5.2-0_*'
      #- 'ssl-cert_*'

  repo:
    - name: AccuInsight
      key: "http://{{ hostvars[groups['accu-pkg-server'][0]]['private_ip'] }}:{{ accu_package_repository_port }}/dists/ubuntu/accuinsight/accuinsight.pub.gpg"
      url: "deb http://{{ hostvars[groups['accu-pkg-server'][0]]['private_ip'] }}:{{ accu_package_repository_port }} ubuntu accuinsight"

