---

- include_tasks: "{{ ansible_os_family | lower }}.yaml"

#- import_tasks: redhat.yaml
#  when: ansible_os_family == 'RedHat'

#- import_tasks: debian.yaml
#  when: ansible_os_family == 'Debian'

