---
# all variables starting with 'accu.*" are defined in vars/ directory.
# all variables starting with 'accu_*" are defined in inventory/accuinsight/groups/all/accuinsight.yaml file.

- name: AccuInsight+ Package Repository | Configure Repository for Server
  when:
    - accu_package_repository_enabled | bool or accu_offline_enabled | bool
    - inventory_hostname in groups['accu-pkg-server']
  become: yes
  block:

    - name: AccuInsight+ Package Repository | Create directories for {{ accu.os.distro }} {{ accu.os.version }}
      file:
        path: "{{ accu_package_repository_path }}/accuinsight"
        state: directory
        mode: '0755'


    - name: AccuInsight+ Package Repository | Synchronize packages 
      synchronize:
        src: "{{ accu_offline_target }}/{{ component }}/files/{{ accu.os.distro }}-{{ accu.os.version }}/"
        dest: "{{ accu_package_repository_path }}/"
        checksum: yes
        delete: yes
      delegate_to: "{{ inventory_hostname }}"


    - name: AccuInsight+ Package Repository | Install web-frontend (Apache)
      shell: |
        # Change directory
        cd {{ accu_package_repository_path }}/accuinsight

        # Install rpm with dependancies.
        # Always return true even if the package is already installed.
        # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#ensuring-success-for-command-and-shell
        rpm -U {{ accu.apache.pkgs | join(' ') }} || /bin/true
      args:
        executable: /bin/bash
        warn: no


    - name: AccuInsight+ Package Repository | Configure web-frontend (path)
      file:
        src: "{{ accu_package_repository_path }}/accuinsight"
        dest: /var/www/html/accuinsight
        state: link


    - name: AccuInsight+ Package Repository | Configure web-frontend (port)
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: "Listen {{ accu_package_repository_port }}"
      notify:
        - Package Repository | Restart


    - name: AccuInsight+ Package Repository | Flush Handlers to restart web-frontend
      meta: flush_handlers


    - name: AccuInsight+ Package Repository | Install metadata tool (createrepo)
      shell: |
        # Change directory
        cd {{ accu_package_repository_path }}/accuinsight

        # Install rpm with dependancies.
        # Always return true even if the package is already installed.
        # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#ensuring-success-for-command-and-shell
        rpm -U {{ accu.createrepo.pkgs | join(' ') }} || /bin/true
      args:
        executable: /bin/bash
        warn: no


    - name: AccuInsight+ Package Repository | Generate createrepo metadata
      shell: |
        createrepo_c {{ accu_package_repository_path }}/accuinsight

        # If umask of 'root' has a strict value (for example, '0026' or '0027' other than default '0022'),
        # repository meta information has to be accessible permission for web frontend.
        find {{ accu_package_repository_path }}/accuinsight -type d -exec chmod 755 {} \;
        find {{ accu_package_repository_path }}/accuinsight -type f -exec chmod 644 {} \;
      args:
        executable: /bin/bash
        warn: no


- name: AccuInsight+ Package Repository | Configure Repository for Client
  when:
    - accu_package_repository_enabled | bool or accu_offline_enabled | bool
  become: yes
  block:

    # READ: https://access.redhat.com/solutions/265523
    - name: AccuInsight+ Package Repository | Change Settings for Online Repositories (Selective Skip)
      when:
        - accu_package_repository_online_handling == 'selective_skip'
      shell: |
        yum-config-manager --setopt={{ item.section }}.skip_if_unavailable=true --setopt={{ item.section }}.timeout=3 --setopt={{ item.section }}.retries=1 --save
      args:
        executable: /bin/bash
        warn: no
      loop: "{{ accu.repo.online }}"
      loop_control:
        label: "{{ item.section }}"


    # READ: https://access.redhat.com/solutions/265523
    - name: AccuInsight+ Package Repository | Change Settings for Online Repositories (All Skip)
      when:
        - accu_package_repository_online_handling == 'all_skip'
      shell: |
        shopt -s nullglob

        for REPO in $(sed -nr 's/^\[(.*)\]/\1/p' /etc/yum.repos.d/*.repo | grep -v AccuInsight)
        do
          yum-config-manager --setopt=${REPO}.skip_if_unavailable=true --setopt=${REPO}.timeout=3 --setopt=${REPO}.retries=1 --save
        done
      args:
        executable: /bin/bash
        warn: no


    # READ: https://access.redhat.com/solutions/265523
    # NOTE: this method doesn't work on RHEL family, use other methods (selective_skip / all_skip / all_skip).
    #       subscription manager reverts back it automatically.
    - name: AccuInsight+ Package Repository | Change Settings for Online Repositories (Selective Disable)
      when:
        - accu_package_repository_online_handling == 'selective_disable'
      ini_file:
        path: "/etc/yum.repos.d/{{ item.repo }}.repo"
        section: "{{ item.section }}"
        option: enabled
        value: "0"
        no_extra_spaces: yes
      loop: "{{ accu.repo.online }}"
      loop_control:
        label: "{{ item.repo }}, {{ item.section }}"


    # READ: https://access.redhat.com/solutions/265523
    - name: AccuInsight+ Package Repository | Change Settings for Online Repositories (All Disable)
      when:
        - accu_package_repository_online_handling == 'all_disable'
      shell: |
        shopt -s nullglob

        for REPO in $(find /etc/yum.repos.d -name "*.repo" | grep -v AccuInsight)
        do
          mv -f ${REPO} ${REPO}.DISABLED-BY-ACCUINSIGHT
        done
      args:
        executable: /bin/bash
        warn: no


    - name: AccuInsight+ Package Repository | Enable AccuInsight+ Repositories for {{ accu.os.distro }} {{ accu.os.version }}
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        file: "{{ item.file }}"
        baseurl: "{{ item.base }}"
        gpgcheck: no
        enabled: yes
      loop: "{{ accu.repo.offline }}"
      loop_control:
        label: "{{ item.desc }}, {{ item.base }}"


    - name: AccuInsight+ Package Repository | Set module_hotfixes to 'True' for AccuInsight+ repository
      when:
        - ansible_distribution_major_version | int == 8
      ini_file:
        path: "/etc/yum.repos.d/{{ item.file }}.repo"
        state: present
        section: "{{ item.name }}"
        option: module_hotfixes
        value: "True"
      loop: "{{ accu.repo.offline }}"
      loop_control:
        label: "{{ item.desc }}"


    - name: AccuInsight+ Package Repository | Clean up repository cache
      command: yum clean all
      args:
        warn: no


    #- name: AccuInsight+ Package Repository | Enable fastestmirror plugin
    #  become: yes
    #  ini_file:
    #    path: /etc/yum/pluginconf.d/fastestmirror.conf
    #    section: main
    #    option: enabled
    #    value: "1"
    #    no_extra_spaces: yes


