---
accu_ceph_block_storage_enabled: true
accu_ceph_object_storage_enabled: true
accu_ceph_filesystem_storage_enabled: true
accu_ceph_ganesha_enabled: true
accu_ceph_data_dir_hostpath: /var/lib/rook
accu_ceph_mon_count: 3
accu_ceph_monitor_dashboard_enabled: true
accu_rook_ceph_admin_pass: admin
accu_rook_ceph_admin_fqdn: ceph.accuinsight.io
accu_ceph_crash_collector_disable: true
accu_ceph_storage_device_name: xvdd
accu_ceph_k8s_manifest_temp_dir: /root/rook-ceph-manifest
accu_ceph_filesystem_pool_name: accufs
accu_ceph_object_storage_fqdn: s3.accuinsight.io
accu_ceph_rgw_instances: 3
accu_ceph_ganesha_instances: 1
accu_ceph_block_pool_name: accu-pool
accu_ceph_block_storage_class_name: accu-ceph-block
accu_ceph_filesystem_storage_class_name: accu-ceph-cephfs
