---

#- name: AccuInsight+ GPU Accelerator | Upgrade Kernel to the latest version
#  become: yes
#  yum:
#    name: kernel
#    state: latest
#  notify:
#    - OS | Reboot

#- name: AccuInsight+ GPU Accelerator | Reboot accelerator nodes before installing driver
#  meta: flush_handlers


- name: AccuInsight+ GPU Accelerator | Add Package Repository 'NVIDIA'
  when:
    - not accu_offline_enabled | bool
    - not accu_package_repository_enabled | bool
  become: yes 
  shell: |
      # for more details, refer to https://nvidia.github.io/nvidia-docker/
      # Supported distributions are CentOS 7/8, RHEL 7.4/7.5/7.6/7.7/8.0/8.1/8.2.
      # All of RHEL-based distributions are using 'centos7' as a distribution id.
      # NOTE: distribution id problem was fixed (2020.08.25)

      DIST=$(. /etc/os-release; echo $ID$VERSION_ID)
      # DIST="centos7"

      curl -s -L https://nvidia.github.io/nvidia-docker/$DIST/nvidia-docker.repo | tee /etc/yum.repos.d/AccuInsight-NVIDIA.repo
  args:
    executable: /bin/bash


- name: AccuInsight+ GPU Accelerator | Set module_hotfixes to 'True' for NVIDIA repository
  when:
    - not accu_offline_enabled | bool
    - not accu_package_repository_enabled | bool
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 8
  become: yes 
  ini_file:
    path: /etc/yum.repos.d/AccuInsight-NVIDIA.repo
    state: present
    section: "{{ item }}"
    option: module_hotfixes
    value: "True"
  loop:
    - nvidia-docker
    - nvidia-container-runtime
    - libnvidia-container


#- name: AccuInsight+ GPU Accelerator | Install NVIDIA driver (Requirements)
#  become: yes
#  yum:
#    name:
#      # for Docker
#      # Use nvidia-container-runtime instead of nvidia-docker2.
#      # nvidia-docker2 makes hard to handle docker daemon.json in ansible level.
#      # https://github.com/nvidia/nvidia-container-runtime#installation
#      #
#      # for CRI-O
#      # cri-o uses standard oci hook for device access.
#      # use nvidia-container-toolkit instead of nvidia-container-runtime.
#      # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/arch-overview.html
#      #
#      # 'nvidia_runtime_package' is defined in 'defaults/main.yaml'.
#      #
#      - '{{ nvidia_runtime_package[kube_cri] }}'
#      - 'kernel-devel'
#      - 'elfutils-libelf-devel'
#      - 'gcc'
#      - 'make'
#    state: latest


# NOTE: Recently on RedHat 8 family, glibc packages were updated from glibc-2.28-101 to glibc-2.28-127.
#       There are some problems to resolve package dependancies. with 2.28-101, need glibc-langpack-en or other locale.
#       but with 2.28-127, all language packages (such as glibc-langpack-XX) are combined to a single package called
#       glibc-all-langpacks.
#
#       To upgrade from 2.28-101 to 2.28-127, glibc-langpack-en should be removed and glibc-all-langpacks should be
#       installed. to do so, --allowerasing option should be passed to yum. but ansible yum module doesn't support it. 
#
#       To resolve this issue, lines above from 53 to 74 were replaced as below.
#
- name: AccuInsight+ GPU Accelerator | Install NVIDIA driver (Requirements)
  become: yes
  shell: |
      yum install -y --allowerasing {{ nvidia_runtime_package[kube_cri] }} kernel-devel elfutils-libelf-devel gcc make
  args:
    executable: /bin/bash
    warn: no


