---

- name: AccuInsight+ GPU Accelerator | Configure Accelerator Nodes
  when:
    - inventory_hostname in groups['kube-master']
  become: yes 
  block:

    - name: AccuInsight+ K8S Tools | Install bash-completion package
      when: ansible_os_family == 'RedHat'
      yum:
        name: bash-completion
        state: present


    - name: AccuInsight+ K8S Tools | Copy kubectx & kubens binaries
      unarchive:
        src: "{{ accu_offline_target }}/{{ component }}/files/{{ item }}"
        dest: /usr/local/bin
        owner: root
        group: root
        remote_src: yes 
        exclude:
          - 'LICENSE'
      loop:
        - 'kubectx_v{{ accu_tools_kubectx_version }}_linux_x86_64.tar.gz'
        - 'kubens_v{{ accu_tools_kubens_version }}_linux_x86_64.tar.gz'


    - name: AccuInsight+ K8S Tools | Copy kubectx & kubens completions
      copy:
        src: "{{ item }}.bash"
        dest: "/etc/bash_completion.d/{{ item }}"
        mode: '0644'
        owner: root
        group: root
      loop:
        - kubectx
        - kubens


    - name: AccuInsight+ K8S Tools | Rename K8S context to 'AccuInsight+'
      shell: |
          if [ $(/usr/local/bin/kubectx | grep -w AccuInsight+) ]
          then
              echo "Already Exists"
          else
              /usr/local/bin/kubectx AccuInsight+=.
          fi 
      args:
        executable: /bin/bash


    - name: AccuInsight+ K8S Tools | Copy powerline-go binary
      copy:
        src: "{{ accu_offline_target }}/{{ component }}/files/powerline-go-linux-amd64"
        dest: /usr/local/bin/powerline-go
        remote_src: yes
        mode: '0755'
        owner: root
        group: root


    - name: AccuInsight+ K8S Tools | Copy powerline-go configuration
      copy:
        src: powerline-go.bash
        dest: /root/.powerline-go
        mode: '0644'
        owner: root
        group: root


    - name: AccuInsight+ K8S Tools | Load powerline-go configuration
      lineinfile:
        dest: /root/.bashrc
        state: present
        line: "source .powerline-go"


    - name: AccuInsight+ K8S Tools | Copy k9scli binary
      unarchive:
        src: "{{ accu_offline_target }}/{{ component }}/files/k9s_v{{ accu_tools_k9scli_version }}_Linux_x86_64.tar.gz"
        dest: /usr/local/bin
        owner: root
        group: root
        remote_src: yes 
        exclude:
          - 'LICENSE'
          - 'README.md'


    - name: AccuInsight+ K8S Tools | Copy kubestr binary
      unarchive:
        src: "{{ accu_offline_target }}/{{ component }}/files/kubestr-v{{ accu_tools_kubestr_version }}-linux-amd64.tar.gz"
        dest: /usr/local/bin
        owner: root
        group: root
        remote_src: yes 
        exclude:
          - 'LICENSE'
          - 'README.md'


