---

# Use 'apt-cache madison docker-ce docker-ce-cli' command for checking available packages in docker repository.
docker_pkg_version: "5:{{ docker_version }}~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"


