---

- name: Container Management Tool | Restart
  become: yes 
  systemd:
    name: docker
    state: restarted
    enabled: yes 
    daemon_reload: yes 


- name: Container Management Tool | Wait for Ready
  become: yes 
  command: docker images
  register: result
  until: result is succeeded
  retries: 10
  delay: 5


