---
# Playbook for AccuInsight+ Loki

- name: AccuInsight+ Loki
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-loki }

