---
# Playbook for AccuInsight+ Package Repository

- name: AccuInsight+ Package Repository
  hosts: kube-cluster,accu-server
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-package-repository }

