---
# Playbook for AccuInsight+ Chart Registry

- name: AccuInsight+ Chart Registry
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-chartmuseum }


