---
# Playbook for AccuInsight+ NFS provisioner

- name: AccuInsight+ NFS Provisioner
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-nfs-provisioner }


