---
# Playbook for AccuInsight+ Test

- name: AccuInsight+ Test
  hosts: kube-cluster,accu-server
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-test }

