---
# Playbook for AccuInsight+ Helm

- name: AccuInsight+ Helm
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-helm }


