---
# Playbook for AccuInsight+ NFS server

- name: AccuInsight+ NFS server
  hosts: accu-nfs-server
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-nfs-server }


