---
# Playbook for AccuInsight+ Metrics Server

- name: AccuInsight+ Metrics Server
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-metrics-server }


