---
# Playbook for AccuInsight+ Storage Ceph

- name: AccuInsight+ Storage Ceph
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-rook-ceph }


