---
# Playbook for AccuInsight+ GPU accelerator

- name: AccuInsight+ GPU accelerator
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-accelerator }

