---
# Playbook for AccuInsight+ Storage Ceph

- name: AccuInsight+ Helm Operator
  hosts: kube-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: accu-helm-operator }


