---

images:

  - component: accu-accelerator
    list:
      - tags: nvidia/k8s-device-plugin:{{ accu_accelerator_device_plugin_version }}
        dest: accu-nvidia
      - tags: nvidia/dcgm-exporter:{{ accu_accelerator_device_metric_version }}
        dest: accu-nvidia

  - component: accu-load-balancer
    list:
      - tags: osixia/keepalived:{{ accu_vip_manager_version }}
        dest: kube-master
      - tags: haproxy:{{ accu_load_balancer_version }}
        dest: kube-master

  - component: accu-chartmuseum
    list:
      - tags: chartmuseum/chartmuseum:v0.12.0
        dest: kube-worker

  - component: accu-harbor
    list:
      - tags: goharbor/chartmuseum-photon:v2.1.2
        dest: kube-worker
      - tags: goharbor/harbor-core:v2.1.2
        dest: kube-worker
      - tags: goharbor/harbor-db:v2.1.2
        dest: kube-worker
      - tags: goharbor/harbor-jobservice:v2.1.2
        dest: kube-worker
      - tags: goharbor/harbor-portal:v2.1.2
        dest: kube-worker
      - tags: goharbor/harbor-registryctl:v2.1.2
        dest: kube-worker
      - tags: goharbor/notary-server-photon:v2.1.2
        dest: kube-worker
      - tags: goharbor/notary-signer-photon:v2.1.2
        dest: kube-worker
      - tags: goharbor/redis-photon:v2.1.2
        dest: kube-worker
      - tags: goharbor/registry-photon:v2.1.2
        dest: kube-worker
      - tags: goharbor/trivy-adapter-photon:v2.1.2
        dest: kube-worker

  - component: accu-helm-operator
    list:
      - tags: fluxcd/helm-operator:1.2.0
        dest: kube-worker

  - component: accu-ingress-controller
    list:
      - tags: k8s.gcr.io/ingress-nginx/controller:v0.41.2
        dest: kube-worker
      - tags: k8s.gcr.io/defaultbackend-amd64:1.5
        dest: kube-worker

  - component: accu-metrics-server
    list:
      - tags: k8s.gcr.io/metrics-server-amd64:v0.3.6
        dest: kube-worker

  - component: accu-monitoring
    list:
      # Prometheus Operator
      - tags: quay.io/prometheus-operator/prometheus-operator:v0.44.0
        dest: kube-worker
      # Prometheus and Alertmanager
      - tags: quay.io/prometheus/prometheus:v2.22.1
        dest: kube-worker
      - tags: quay.io/prometheus/alertmanager:v0.21.0
        dest: kube-worker
      - tags: quay.io/prometheus-operator/prometheus-config-reloader:v0.44.0
        dest: kube-worker
      # Prometheus Node Exporter
      - tags: quay.io/prometheus/node-exporter:v1.0.1
        dest: kube-cluster
      # Kube State Metrics
      - tags: quay.io/coreos/kube-state-metrics:v1.9.7
        dest: kube-worker
      # Grafana
      - tags: grafana/grafana:7.2.1
        dest: kube-worker
      - tags: kiwigrid/k8s-sidecar:1.1.0
        dest: kube-worker

  - component: accu-nfs-provisioner
    list:
      - tags: quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
        dest: kube-worker

  - component: accu-registry
    list:
      - tags: registry:2.7.1
        dest: kube-worker

  - component: accu-rook-ceph
    list:
      - tags: rook/ceph:v{{ accu_rook_ceph_version }}
        dest: accu-ceph
      - tags: ceph/ceph:v{{ accu_ceph_image_version }}
        dest: accu-ceph
      - tags: quay.io/cephcsi/cephcsi:v3.2.0
        dest: accu-ceph
      - tags: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
        dest: accu-ceph
      - tags: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.0
        dest: accu-ceph
      - tags: k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
        dest: accu-ceph
      - tags: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.0
        dest: accu-ceph
      - tags: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
        dest: accu-ceph

  - component: calico
    list:
      - tags: docker.io/calico/cni:v{{ cni_calico_version }}
        dest: kube-cluster
      - tags: docker.io/calico/kube-controllers:v{{ cni_calico_version }}
        dest: kube-cluster
      - tags: docker.io/calico/node:v{{ cni_calico_version }}
        dest: kube-cluster
      - tags: docker.io/calico/pod2daemon-flexvol:v{{ cni_calico_version }}
        dest: kube-cluster

  - component: kubernetes
    list:
      - tags: k8s.gcr.io/kube-proxy:v{{ kube_version }}
        dest: kube-cluster
      - tags: k8s.gcr.io/kube-apiserver:v{{ kube_version }}
        dest: kube-master
      - tags: k8s.gcr.io/kube-controller-manager:v{{ kube_version }}
        dest: kube-master
      - tags: k8s.gcr.io/kube-scheduler:v{{ kube_version }}
        dest: kube-master
      - tags: k8s.gcr.io/etcd:{{ supported_etcd }}
        dest: kube-master
      - tags: k8s.gcr.io/coredns:{{ supported_coredns }}
        dest: kube-cluster
      - tags: k8s.gcr.io/pause:{{ supported_pause }}
        dest: kube-cluster


# SupportedEtcdVersion constant in kubeadm source code.
# https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L464-L475
matrix_etcd:
  '1.13': "3.2.24"
  '1.14': "3.3.10"
  '1.15': "3.3.10"
  '1.16': "3.3.17-0"
  '1.17': "3.4.3-0"
  '1.18': "3.4.3-0"
  '1.19': "3.4.13-0"
  '1.20': "3.4.13-0"
  '1.21': "3.4.13-0"

supported_etcd: "{{ matrix_etcd[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')] }}"


# PauseVersion constant in kubeadm source code.
matrix_pause:
  '1.13': "3.1" # https://github.com/kubernetes/kubernetes/blob/release-1.13/cmd/kubeadm/app/constants/constants.go#L256
  '1.14': "3.1" # https://github.com/kubernetes/kubernetes/blob/release-1.14/cmd/kubeadm/app/constants/constants.go#L263
  '1.15': "3.1" # https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/constants/constants.go#L264
  '1.16': "3.1" # https://github.com/kubernetes/kubernetes/blob/release-1.16/cmd/kubeadm/app/constants/constants.go#L266
  '1.17': "3.1" # https://github.com/kubernetes/kubernetes/blob/release-1.17/cmd/kubeadm/app/constants/constants.go#L269
  '1.18': "3.2" # https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kubeadm/app/constants/constants_unix.go#L26
  '1.19': "3.2" # https://github.com/kubernetes/kubernetes/blob/release-1.19/cmd/kubeadm/app/constants/constants_unix.go#L26
  '1.20': "3.2" # https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/constants/constants_unix.go#L26
  '1.21': "3.2" # https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants_unix.go#L26

supported_pause: "{{ matrix_pause[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')] }}"


# CoreDNSVersion contant in kubeadm source code.
matrix_coredns:
  '1.13': "1.2.6" # https://github.com/kubernetes/kubernetes/blob/release-1.13/cmd/kubeadm/app/constants/constants.go#L334-L335
  '1.14': "1.3.1" # https://github.com/kubernetes/kubernetes/blob/release-1.14/cmd/kubeadm/app/constants/constants.go#L341-L342
  '1.15': "1.3.1" # https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/constants/constants.go#L333-L334
  '1.16': "1.6.2" # https://github.com/kubernetes/kubernetes/blob/release-1.16/cmd/kubeadm/app/constants/constants.go#L335-L336
  '1.17': "1.6.5" # https://github.com/kubernetes/kubernetes/blob/release-1.17/cmd/kubeadm/app/constants/constants.go#L338-L339
  '1.18': "1.6.7" # https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kubeadm/app/constants/constants.go#L339-L340
  '1.19': "1.7.0" # https://github.com/kubernetes/kubernetes/blob/release-1.19/cmd/kubeadm/app/constants/constants.go#L331-L332
  '1.20': "1.7.0" # https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/constants/constants.go#L349-L350
  '1.21': "1.7.0" # https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L349-L350

supported_coredns: "{{ matrix_coredns[kube_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2')] }}"

