---
# Calico Container Network Interface v3.17.1
#  - curl https://docs.projectcalico.org/v3.17/manifests/calico.yaml -O
#  - https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises
#  - https://docs.projectcalico.org/getting-started/clis/calicoctl/install


# READ: https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager
- name: AccuInsight+ Kubernetes | CNI | Check if NetworkManager is running
  become: yes
  command: "pidof NetworkManager"
  register: nm_status
  changed_when: false
  failed_when: false


# READ: https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager
- name: AccuInsight+ Kubernetes | CNI | Prevent NetworkManager from controlling Calico interfaces
  when: nm_status.rc == 0
  become: yes
  copy:
    dest: /etc/NetworkManager/conf.d/calico.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico
  delegate_to: "{{ item }}"
  loop: "{{ groups['kube-cluster'] }}"
  run_once: true
  notify:
    - CNI | Calico | Reload NetworkManager


# NOTE: 'private_ip' is referenced from inventory file.
- name: AccuInsight+ Kubernetes | CNI | Get default cidr for calico nodes
  become: yes
  shell:
    ip -o address show | grep {{ private_ip }} | awk '{print $4}'
  args:
    executable: /bin/bash
  register: node_default_cidr


- name: AccuInsight+ Kubernetes | CNI | Set default cidr for calico nodes
  set_fact:
    calico_node_cidr: "{{ node_default_cidr.stdout }}"


- name: AccuInsight+ Kubernetes | CNI | Create menifests directory for Calico
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  file:
    path: "{{ accu_manifests_location}}/{{ component }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: true


- name: AccuInsight+ Kubernetes | CNI | Create manifests for Calico
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "{{ accu_manifests_location }}/{{ component }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    # SOURCE: https://docs.projectcalico.org/v3.17/manifests/calico.yaml
    - 'calico.yaml'
    # READ: https://docs.projectcalico.org/networking/ip-autodetection
    #       https://docs.projectcalico.org/reference/resources/node
    #       https://docs.projectcalico.org/networking/node
    - 'calico-node-default-cidr.yaml'


- name: AccuInsight+ Kubernetes | CNI | Initialize Calico
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
    kubectl apply -f {{ accu_manifests_location }}/{{ component }}/calico.yaml
  args:
    executable: /bin/bash
  run_once: true
  register: cni_result
  failed_when: cni_result is failed
  until: cni_result is succeeded
  retries: 3
  delay: 60


- name: QKS Kubernetes | CNI | Initialize Calico (complex autodetection)
  when:
    - cni_calico_cidr_autodetection_method == 'complex'
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
    kubectl apply -f {{ qks_manifests_location }}/{{ component }}/calico-node-default-cidr.yaml
  args:
    executable: /bin/bash
  run_once: true
  register: cni_result
  failed_when: cni_result is failed
  until: cni_result is succeeded
  retries: 3
  delay: 60


- name: AccuInsight+ Kubernetes | CNI | Wait for Calico to complete
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
    kubectl -n kube-system get pods | grep calico-node
  args:
    executable: /bin/bash
  run_once: true
  register: calico_node
  until: calico_node.stdout.count("Running") >= ( groups['kube-master'] | count )
  retries: 10
  delay: 30


# Rarely, coredns get hung after deploying calico.
- name: AccuInsight+ Kubernetes | CNI | Restart CoreDNS
  when:
    - inventory_hostname in groups['kube-master']
  become: yes
  shell: |
    kubectl -n kube-system delete pods -l k8s-app=kube-dns
  args:
    executable: /bin/bash
  run_once: true


