---
# Calico Container Network Interface v3.17.1
#  - curl https://docs.projectcalico.org/manifests/calico.yaml -O
#  - https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises
#  - https://docs.projectcalico.org/getting-started/clis/calicoctl/install


# READ: https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager
- name: AccuInsight+ Kubernetes | CNI | Check if NetworkManager is running
  become: yes 
  command: "pidof NetworkManager"
  register: nm_status
  changed_when: false
  failed_when: false


# READ: https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager
- name: AccuInsight+ Kubernetes | CNI | Prevent NetworkManager from controlling Calico interfaces
  when: nm_status.rc == 0
  become: yes
  copy:
    dest: /etc/NetworkManager/conf.d/calico.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico
  delegate_to: "{{ item }}"
  loop: "{{ groups['kube-cluster'] }}"
  run_once: true
  notify:
    - CNI | Calico | Reload NetworkManager


- name: AccuInsight+ Kubernetes | CNI | Create menifests directory for Calico
  become: yes 
  file:
    path: "{{ accu_manifests_location}}/{{ component }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: true


- name: AccuInsight+ Kubernetes | CNI | Create manifests for Calico
  become: yes 
  template:
    src: calico.yaml.j2
    dest: "{{ accu_manifests_location }}/{{ component }}/calico.yaml"
    owner: root
    group: root
    mode: '0644'


- name: AccuInsight+ Kubernetes | CNI | Initialize Calico
  when: inventory_hostname == groups['kube-master'][0]
  become: yes 
  shell: |
    kubectl apply -f {{ accu_manifests_location }}/{{ component }}/calico.yaml
  args:
    executable: /bin/bash
  register: cni_result
  failed_when: cni_result is failed
  until: cni_result is succeeded
  retries: 3
  delay: 60


- name: AccuInsight+ Kubernetes | CNI | Wait for Calico to complete
  when: inventory_hostname == groups['kube-master'][0]
  become: yes 
  shell: |
    kubectl -n kube-system get pods | grep calico-node
  args:
    executable: /bin/bash
  register: calico_node
  until: calico_node.stdout.count("Running") >= ( groups['kube-master'] | count )
  retries: 10
  delay: 30


# Rarely, coredns get hung after deploying calico.
- name: AccuInsight+ Kubernetes | CNI | Restart CoreDNS
  when: inventory_hostname == groups['kube-master'][0]
  become: yes 
  shell: |
    kubectl -n kube-system delete pods -l k8s-app=kube-dns
  args:
    executable: /bin/bash


