---

- name: AccuInsight+ Kubernetes | Set label for master nodes
  become: yes
  shell: |
      kubectl label node {{ item }} node-role.kubernetes.io/master= --overwrite
  args:
    executable: /bin/bash
  run_once: true
  loop: "{{ groups['kube-master'] }}"


- name: AccuInsight+ Kubernetes | Set label for worker nodes
  become: yes
  shell: |
      kubectl label node {{ item }} node-role.kubernetes.io/worker= --overwrite
  args:
    executable: /bin/bash
  run_once: true
  loop: "{{ groups['kube-worker'] }}"


- name: AccuInsight+ Kubernetes | Set label for ceph nodes
  when:
    - accu_rook_ceph_enabled | bool
  become: yes
  shell: |
      kubectl label node {{ item }} node-role.kubernetes.io/ceph=storage --overwrite
  args:
    executable: /bin/bash
  run_once: true
  loop: "{{ groups['accu-ceph'] }}"


- name: AccuInsight+ Kubernetes | Set label for accelerator nodes
  when:
    - accu_accelerator_enabled | bool
  become: yes
  shell: |
      kubectl label node {{ item }} node-role.kubernetes.io/accelerator=nvidia --overwrite
  args:
    executable: /bin/bash
  run_once: true
  loop: "{{ groups['accu-nvidia'] }}"


# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation
- name: AccuInsight+ Kubernetes | Set taint for master nodes
  become: yes
  shell: |
    if [ "{{ kube_master_node_taint }}" == "True" ]
    then
      kubectl taint node {{ item }} node-role.kubernetes.io/master=:NoSchedule --overwrite
    else
      kubectl taint node {{ item }} node-role.kubernetes.io/master=:NoSchedule- || /bin/true
    fi
  args:
    executable: /bin/bash
  run_once: true
  loop: "{{ groups['kube-master'] }}"


- name: AccuInsight+ Kubernetes | Set taint for ceph nodes
  when:
    - accu_rook_ceph_enabled | bool
  become: yes
  shell: |
    if [ "{{ accu_rook_ceph_node_taint }}" == "True" ]
    then
      kubectl taint node {{ item }} accuinsight.io/ceph=:NoSchedule --overwrite
    else
      kubectl taint node {{ item }} accuinsight.io/ceph=:NoSchedule- || /bin/true
    fi
  args:
    executable: /bin/bash
  run_once: true
  loop: "{{ groups['accu-ceph'] }}"


- name: AccuInsight+ Kubernetes | Set taint for accelerator nodes
  when:
    - accu_accelerator_enabled | bool
  become: yes
  shell: |
    if [ "{{ accu_accelerator_node_taint }}" == "True" ]
    then
      kubectl taint node {{ item }} accuinsight.io/accelerator=:NoSchedule --overwrite
    else
      kubectl taint node {{ item }} accuinsight.io/accelerator=:NoSchedule- || /bin/true
    fi
  args:
    executable: /bin/bash
  run_once: true
  loop: "{{ groups['accu-nvidia'] }}"


