---

- name: AccuInsight+ Collector | Collect Images for Offline Installation
  when:
    - inventory_hostname == groups['accu-pkg-server'][0]
  become: yes
  block:

#    - name: AccuInsight+ Collector | Load List of Images
#      include_vars: images.yaml


    - name: AccuInsight+ Collector | Install Container Management Tool
      when:
        - ansible_os_family == 'RedHat'
      yum:
# NOTE: At this time (2021.04.20), there are some package dependency problem with containers-common.
#       the latest podman requires containers-common-4:1-15 which has a dependency (container-selinux >= 2:2.160.0-1)
#       but RedHat changed package naming convention from 2:2.160.0-x to 2.160.0-x (without Epoch).
#       Currently, we use a previous version of podman-2.2.1 instead of 3.0.x and have to wait for RedHat to solve this issue.
#
#       Now (2021.04.26), replaced podman with docker as a container management tool to resolve bad package naming conventions with RedHat family.
        name:
          - docker-ce 
          - pigz
        state: latest
        update_cache: yes
      notify:
        - Container Management Tool | Restart
        - Container Management Tool | Wait for Ready


    - name: AccuInsight+ Collector | Install Container Management Tool
      when:
        - ansible_os_family == 'Debian'
      apt:
        name:
          - docker-ce
          - pigz
        state: latest
      notify:
        - Container Management Tool | Restart
        - Container Management Tool | Wait for Ready


    - name: AccuInsight+ GPU Accelerator | Flush Handlers for Container Management Tool
      meta: flush_handlers


    - name: AccuInsight+ Collector | Collect Images
      shell: |
        # Create directoryies.
        mkdir -p {{ accu_collector_target }}/{{ item.0.component }}/images

        # Delete *.lst (image information) file if it esists.
        # rm -rf {{ accu_collector_target }}/{{ item.0.component }}/images/*.lst

        # Create dest directory
        mkdir -p {{ accu_collector_target }}/{{ item.0.component }}/images/{{ item.1.dest }}

        # Pull images
        docker pull {{ item.1.tags }}

        # Save images (This step will be skipped if the saved images already exist.)
        FILE="{{ accu_collector_target }}/{{ item.0.component }}/images/{{ item.1.dest }}/{{ item.1.tags | replace(    '/', '--') | replace(':', '--') }}.tar.gz"

        # NOTE: Replaced gzip with pigz for better performance (multicore compress).
        if [ ! -f ${FILE} ];
        then
          docker save {{ item.1.tags }} | pigz -9 > ${FILE}
        fi

        # Delete images after saving.
        docker rmi {{ item.1.tags }}

        ## Update images information. this file is not used in any codes but just information.
        echo {{ item.1.tags }} >> {{ accu_collector_target }}/{{ item.0.component }}/images/{{ item.0.component }}.lst
      args:
        executable: /bin/bash
        warn: no
      loop: "{{ images | subelements('list') }}"
      loop_control:
        label: "{{ item.0.component }}, {{ item.1.tags }}"


    - name: AccuInsight+ Collector | Synchronize Images
      synchronize:
        mode: pull
        src: "{{ accu_collector_target }}/{{ item.component }}/images"
        dest: "{{ accu_offline_source }}/{{ item.component }}"
        checksum: yes
        delete: yes
      loop: "{{ images }}"
      loop_control:
        label: "{{ item.component }}"


