---

- include_tasks: packages-redhat.yaml
  when:
    - accu_collector_gathering_packages
    - ansible_os_family == 'RedHat'

- include_tasks: packages-debian.yaml
  when:
    - accu_collector_gathering_packages
    - ansible_os_family == 'Debian'

- include_tasks: charts.yaml
  when: accu_collector_gathering_charts

- include_tasks: files.yaml
  when: accu_collector_gathering_files

- include_tasks: images.yaml
  when: accu_collector_gathering_images

- include_tasks: clean.yaml
  when: accu_collector_cleanup

