---

- name: AccuInsight+ Collector | Collect Packages and Dependancies for Offline Installation
  when:
    - inventory_hostname == groups['accu-pkg-server'][0]
  become: yes
  block:

#    - name: AccuInsight+ Collector | Load List of OS Packages
#      include_vars: packages-debian.yaml


    - name: AccuInsight+ Collector | Add Package Repository (Repository KEY)
      apt_key:
        url: "{{ item.key }}"
        state: present
      loop: "{{ debian.repos }}"
      loop_control:
        label: "{{ item.name }}"


    - name: AccuInsight+ Collector | Add Package Repository (Repository URL)
      apt_repository:
        repo: "{{ item.url }}"
        filename: "Collector-{{ item.name }}"
        state: present
        mode: '0644'
        update_cache: yes
      loop: "{{ debian.repos }}"
      loop_control:
        label: "{{ item.name }}"


    # APT preferences need to be set for handling packages which have same version on multiple repositories or multiple version of same package.
    # To check package candicate version which is selected by apt system, use 'apt-cache policy <package name>' command.
    # APT preferences help us to keep a specific version of packages and to simplify name of package to be installed.
    #
    # DOCS: https://askubuntu.com/questions/135339/assign-highest-priority-to-my-local-repository
    #       http://manpages.ubuntu.com/manpages/bionic/man5/apt_preferences.5.html
    #       https://www.debian.org/doc/manuals/apt-howto/ch-apt-get.en.html#s-pin
    - name: AccuInsight+ Collector | Set Packege Repository (Repository Preferences)
      copy:
        dest: /etc/apt/preferences.d/Collector
        owner: root
        group: root
        mode: '0644'
        content: |
          # for kubernetes
          Package: kubeadm kubelet kubectl
          Pin: version {{ kube_version }}*
          Pin-Priority: 1001

          # for cri-o
          Package: cri-o
          Pin: version {{ crio_version }}*
          Pin-Priority: 1001

          # for docker
          Package: docker-ce docker-ce-cli
          Pin: version 5:{{ docker_version }}*
          Pin-Priority: 1001

          # for containerd
          Package: containerd.io
          Pin: version {{ containerd_version }}*
          Pin-Priority: 1001

          # for ceph-common
          Package: *
          Pin: release o=ceph.com
          Pin-Priority: 1001


    - name: AccuInsight+ Collector | Add Package Repository 'NVIDIA'
      shell: |
          # for more details, refer to https://nvidia.github.io/nvidia-docker/
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
          DIST=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/$DIST/nvidia-docker.list | tee /etc/apt/sources.list.d/Collector-NVIDIA.list
      args:
        executable: /bin/bash


    - name: AccuInsight+ Collector | Set facts for Packages and Locations
      set_fact:
        packages: "{{ (debian.pkgs.core + debian.pkgs.reqs) | join(' ') }}"
        down_location: "{{ accu_collector_target }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}/accuinsight"
        pull_location: "{{ accu_offline_source }}/accu-package-repository/files/accu-pkg-server/{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}"


    - name: AccuInsight+ Collector | Collect Packages and Dependancies
      shell: |
        # Create download directory
        mkdir -p {{ down_location }}; cd {{ down_location }}

        # Update repository metadata.
        apt update

        # Download packages defined in 'debian.pkgs' and all of their dependancies recursively even if they were already installed.
        apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces {{ packages }} | grep "^\w" | sort -u | xargs apt download {{ packages }}
      args:
        executable: /bin/bash
        warn: no


    - name: AccuInsight+ Collector | Prepare Packages (directory)
      become: no
      file:
        path: "{{ pull_location }}"
        state: directory
        recurse: yes
        mode: '0755'
      delegate_to: localhost


    - name: AccuInsight+ Collector | Synchronize Packages
      synchronize:
        mode: pull
        src: "{{ down_location }}"
        dest: "{{ pull_location }}"
        checksum: yes 
        delete: yes


